name: Test Actions
on:
  push:
    branches:
      - main
jobs:
   test-job:
     runs-on: ubuntu-latest
     
     steps:
       - name: print hello
         run: echo"hello developer"

       - name: list files
         run : ls -al
     
